production:
  adapter: mysql
  database: coolpur_sales
  encoding: utf8
  timeout: 5000
  username: coolpur
  password: aexGkQ5SrP
  host: localhost
development:
  adapter: mysql
  database: coolpur_sales
  encoding: utf8
  timeout: 5000
  username: coolpur
  password: aexGkQ5SrP
  host: localhost
test:
  adapter: mysql
  database: coolpur_test
  encoding: utf8
  timeout: 5000
  username: coolpur
  password: aexGkQ5SrP
  host: localhost